services:
  openclawbot:
    image: ghcr.io/vxwork/openclaw-docker/openclaw:linux_latest  
    container_name: openclawbot
    #ports:
    #  - "18789:18789"
    networks:
      - openclaw_network
    volumes:
      - ./config:/root/.openclaw
    environment:
      - NODE_ENV=production
      - OPENCLAW_GATEWAY_TOKEN=582f027860c56071d5397404ff621f92c7522a0ebf645d079ffafabfed7298e2
      - OPENCLAW_SKIP_CONFIG=true
    restart: unless-stopped

networks:
  openclaw_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.15.119.0/24
